### ISSUE TITLE
Implement Objects

### ISSUE THREAD

**Issue by liquidcronos** [liquidcronos/Lucid#1]
an Archictecture for Objects needs to be implemented that allows for manipulation by Lucy and Ego.
it should be able to allow for emergent puzzle solving

**Comment by Luichang** [comment]
Added functions #8 that could not be tested yet. Attempted to use the call back of area_entered, failed on my end. Found out, that by creating a new scene with it's properties, that items needing to be relative to each other should remain relative to each other on the main scene. Recommend more research

**Comment by Luichang** [comment]
Reworked the Objects class in #8 and fixed bug, where areas would not register. The Object class is ready to have sub-nodes going from it to start the game mechanics part. The Object has 4 areas for Lucy to interact in and one for Ego, Egos area does not detect, whether a body entered, but an area, as if I were to give him a collision box he would not be able to enter walls anymore.
